# Generated by Django 2.2.5 on 2019-11-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
