# Generated by Django 2.2.5 on 2019-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_note_updation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='updation_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
